Repository shivangdubey/HacktoberFest2020, pull requests merged in 2020-10, with the labels that each got.

#88 Create ArrayRotation.java
  java/ArrayRotation.java
Labels: hacktoberfest-accepted

#63 Making a hangman game using Python
  Hangman_Game.py
Labels: hacktoberfest-accepted

#56 Create BubbleSort.py
  BubbleSort.py
Labels: hacktoberfest-accepted

#74 adding a email sending file
  python/sending email.py
Labels: hacktoberfest-accepted

#65 Created an Encrypter using pseudo random series
  PseudoRandomSeriesEncrypter.py
Labels: hacktoberfest-accepted

#49 Added Calculator readme
  README.md
  images/input.png
  images/output.png
Labels: conflicting

#133 Kruskals algorithm in C
  c/Kruskals.c
Labels: hacktoberfest-accepted

#131 Prims algorithm in C++
  c++/prims.cpp
Labels: hacktoberfest-accepted

#126 Added new algorithms
  java/Anagram.java
  java/SecondHighestNumber.java
Labels: hacktoberfest-accepted

#119 fibonacci_DP.cpp
  cpp/DP Basics Using CPP/fibonacci_DP.cpp
Labels: hacktoberfest-accepted

#117 bogosort in python
  python/bogosort.py
Labels: hacktoberfest-accepted

#112 fibonacci.py
  fibonacci.py
Labels: hacktoberfest-accepted

#75 Integrating google sheets with python
  python/Google Sheets/sheets_analysis.py
Labels: hacktoberfest-accepted

#82 Create cyberRECKON_CircularDoublyLinkedList.c
  c/cyberRECKON_CircularDoublyLinkedList.c
Labels: hacktoberfest-accepted

#171 A menu-driven Pattern Program
  c++/PATTERN.CPP
Labels: hacktoberfest-accepted

#147 Quick Sort Algorithm in java
  java/QuickSort.java
Labels: hacktoberfest-accepted

#137 Circular Queue in C
  c/Circular_queue.c
Labels: hacktoberfest-accepted

#134 Selection Sort in C
  c/Selection_sort.c
Labels: hacktoberfest-accepted

#110 binarysearch.py
  python/binarysearch.py
Labels: hacktoberfest-accepted

#235 Created selectionsort.py
  python/selectionsort.py
Labels: hacktoberfest-accepted

#236 Find Table Of Any Number
  python/Find Table Of Any Number
Labels: no_description

#303 String palindrome or not.cpp
  c++/given_string_is_palindrome_or_not.cpp
Labels: no_description

#338 Python file for Drinking Water notification
  Chatting App/client.js
  Chatting App/index.html
  Chatting App/index.js
  Chatting App/main.css
  Chatting App/package-lock.json
  Chatting App/package.json
  python/DesktopNotification.py
  python/Resume Checker/explore_microdoft.docx
  python/Resume Checker/resume - for merge.docx
  python/Resume Checker/resume_Checker.py
Labels: hacktoberfest-accepted, no_description

#433 Create Asteroid_Collision_Solution.py
  python/Asteroid_Collision_Solution.py
  python/Best_Time_to_Buy_and_Sell_Stock.py
Labels: hacktoberfest-accepted

#455 Python Password Generator
  python/Python Password Generator/README.md
  python/Python Password Generator/generate.py
  python/Scrape URLs/README.md
  python/Scrape URLs/scraper.py
Labels: hacktoberfest-accepted
